In [129]:
import numpy as np

In [130]:
Numpy = np.array([[1, 2, 3, 3, 1], 
                [6, 8, 11, 10, 7]])

In [131]:
Numpy

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [132]:
mean_a = Numpy.mean(axis=1) 

In [133]:
mean_a 

array([2. , 8.4])

In [134]:
a = Numpy

In [135]:
a_centered = a.T - mean_a.T

In [136]:
print(a_centered.shape)
print(a_centered)

(5, 2)
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [146]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [147]:
a_centered_sp

8.0

In [148]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

In [152]:
np.cov(a)[0, 1]

2.0